### ISSUE TITLE
When only one result is displayed is not necessary to display the text

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#167]
Environment

Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Complete search field with "MiG-29".

actual: observe the text "End of results" even only one result was returned.

expected: in this case do not display this text.

see attach!

![end-of-results](https://cloud.githubusercontent.com/assets/18361424/14405616/3112d934-fe9b-11e5-84dd-77723c5c4aed.png)

**Comment by callmekatootie** [comment]
Not a issue

**Comment by onetliviunicu** [comment]
Why?

**Comment by callmekatootie** [comment]
This is actually a duplicate issue where special characters need handling (- character) - because of which, the exact user was not shown - instead, if you see the title, the app searched for -29 and found only one user - hence the end of results is shown because it could not find any other user for 29

**Comment by onetliviunicu** [comment]
I understand, so this result is because the system search for an invalid character as -29, but what you say then about the text End of results which is displayed when only one data record is displayed.I think this text must not be displayed!

**Comment by callmekatootie** [comment]
@fnisen @nlitwin I assume the end of results is shown to indicate to the user that they need not scroll further since there are no results? (else, for infinite scroll they have to keep scrolling) - so, if no scrollbar is shown, then should "End of Results" be shown (because infinite scroll was not triggered)?

**Comment by onetliviunicu** [comment]
Please also see the issue https://github.com/appirio-tech/topcoder-app-r/issues/48.In this issue the competitor require as "End of results" to be shown even one results which is really wrong!

**Comment by onetliviunicu** [comment]
Please set a comment with only one reason to have the text "End of results" when you receive only one returned record!

**Comment by fnisen** [comment]
@onetliviunicu - yes, you're right, we allowed #48, which is why we can't allow this one. To keep the experience consistent, we're saying always show "End of results" at the end of all returned results.

**Comment by onetliviunicu** [comment]
ok, thank you!
