### ISSUE TITLE
Android - search is performed even no characters set

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#171]
HTC One M9
Android 6.0
Chrome

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Go to main menu.

3) Set focus on search field without set any character.

4) Press enter.

--------------------------------------------------------------------------------------------------

actual: the search is performed even no characters was set in field.

expected: do not allow to be performed the search when no characters are set.

-----------------------------------------------------------------------------------------------------

**Comment by callmekatootie** [comment]
You can't report the same issue in multiple devices in multiple tickets

**Comment by onetliviunicu** [comment]
hy, why this issue is not accepted.I don't tested on "multiple devices".To perform testing on this competition I used only a mobile device HTC One M9 and a desktop pc HP.To find this issue the testing was performed separatly and this issue was founded on HTC One M9 device.Why is not accepted?

**Comment by callmekatootie** [comment]
The issue is taken into consideration - not the device or the browser..

A participant cannot report the same issue in multiple browsers or devices - that way, each ticket created in this contest can be copied over and a new ticket can be created for each of the browser and device in scope for this contest!

Your issues has already been reported earlier here - https://github.com/appirio-tech/topcoder-app-r/issues/22
