### ISSUE TITLE
[Common] Search is not working as expected

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#26]
Description
-----------------------------------------------------------------
[Common] Search is not working as expected

Steps
-----------------------------------------------------------------
- Open the Web Page

- Click Search

- Enter 'Windows Phone'

- Check the result

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- Must search the People, challenge and content

Actual result
-----------------------------------------------------------------
[Common] Search is not working as expected

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 
FF 45.0.1, 
IE 11
iPhone 6s, Safari

Image/Video/JS Log
-----------------------------------------------------------------

**Comment by callmekatootie** [comment]
QA has this working:

![image](https://cloud.githubusercontent.com/assets/2317133/14450316/e6467742-009a-11e6-8939-d443a846acec.png)

**Comment by nlitwin** [comment]
I think this isn't working. The skill Windows Phone should only show members with that skill, and I believe many of these members do not have the skill. Also, since Windows Phone is a skill, it should be highlighted first in the skills list as `Skills: #Windows Phone #....` There are many many skills though, so I think this bug is the same for other skills that are not working in a similar manner to this one.
