### ISSUE TITLE
End of results is missing when there’s only 1 result

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#48]
Mac 10.11.4 + FF45.0.1

1. open https://www.topcoder-qa.com/search/members/?q=nhzp339
2. observe the bottom

expected: "End of results" should be shown

actual: see screenshot
![qq20160409-55 2x](https://cloud.githubusercontent.com/assets/4590317/14402675/4bbddd50-fe6f-11e5-8b42-109f4cfd5f3e.png)

**Comment by callmekatootie** [comment]
@fnisen Bug? I think the end of results is shown only when showing the Top members or members matching text are shown - not for direct match

**Comment by nlitwin** [comment]
The "End of results" message was only built for appearing at the end of username matches, since you know that the exact match can only be 1, the top member leaderboard is always 10, and the username matches could be hundreds. I think there was another issue logged that also mentioned that there is no "End of results" message below the leaderboard.

**Comment by fnisen** [comment]
@callmekatootie, @nlitwin - let's allow this one. I think it's a reasonable expectation.
